### ISSUE TITLE
2.0: UI – CATALOG —> Fixed header with title, filter, and submenu; position filter to the center

### ISSUE THREAD

**Issue by gopherstein** [supergiant/control#1095] opened 2018-12-03 13:20 UTC
![Screen Shot 2018-12-03 at 1:20 PM](http://marker.screenshots.prod.s3.amazonaws.com/9223767ef1634b4a9b465be989e6ed69-1543843228048.png)

**Summary:**
1.  Fixed header with title, filter, and submenu
2. Move filter to center

**Steps to Reproduce:** 
1. Spin up minimum 1 cluster
2. Got to Catalog from the top menu
3. Open one of the displayed charts/apps

**Notes:**

Design specs: https://xd.adobe.com/spec/3c5108bd-fd7f-467f-47f8-837ef0d07611-4a60/screen/a0478d4a-7625-4596-a31d-8926e4c27a27/sg2-apps-list-sg/

P. S. I suppose layout has been changed when Joe fixed other issue.

---
### More Info

**Reported by:** Taras Hetmanchuk (taras@qbox.io)
**Source URL**: [http://localhost:4200/catalog/supergiant](http://localhost:4200/catalog/supergiant)

<table><tr><td><strong>Browser</strong></td><td>Chrome 70.0.3538.102</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr></table>

**Comment by hetmanchuk** [comment] 2018-12-03 13:31
@gopherstein this need to be deleted, duplicate of #1094

**Comment by eldridgeh** [comment] 2018-12-03 14:30
Closing due to @hetmanchuk request.

**Closed by eldridgeh** 2018-12-03 14:30 UTC
Labels: bug
