### ISSUE TITLE
2.0: API - Ulimit on boxes needs to be set during provisioning.

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#916] opened 2018-11-16 23:00 UTC
**Short Summary:**
Ulimit on boxes need to be set on boxes while provisioning
**Steps to Reproduce:**
n/a
**Expected Results:**
n/a
**Actual Results:**
n/a
The ulimit for open files looks to be set at 1024, this needs to be increased to something high

**Comment by stgleb** [comment] 2018-11-21 23:16
@eldridgeh @saheienko Isn't this enough?

AWS

```
root@ip-172-31-13-132:~# ulimit -n
300000
```

DO

```
root@TestLimit-node-38aa:~# ulimit -n
300000
```

**Comment by gopherstein** [comment] 2018-11-21 23:19
Should be fine, just ensure it persists past reboot

**Comment by stgleb** [comment] 2018-11-21 23:35
it persists on AWS

```
cat /etc/security/limits.conf 
root soft  nofile 300000
root hard  nofile 300000
```
but in DO it doesn't

**Comment by saheienko** [comment] 2018-11-28 12:30
#1005 doesn't solve this issue.

**Comment by stgleb** [comment] 2018-12-01 23:51
Please, add steps to reproduce. I downsize ulimit on my local machine to 256 
but can't reproduce it.

**Comment by stgleb** [comment] 2018-12-02 22:18
Well, right after cluster is provisioned count of network connection constantly grows, profiling of goroutines shows leak 

```
goroutine profile: total 1808
896 @ 0x42fb5b 0x42ae99 0x42a546 0x497cea 0x497dfd 0x498b49 0x5bb79f 0x5cf298 0x62b1f9 0x62b6fd 0x62ec81 0x6e6465 0x516076 0x5161cf 0x6e6fb2 0x45d951
#	0x42a545	internal/poll.runtime_pollWait+0x65	/usr/local/go/src/runtime/netpoll.go:173
#	0x497ce9	internal/poll.(*pollDesc).wait+0x99	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85
#	0x497dfc	internal/poll.(*pollDesc).waitRead+0x3c	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90
#	0x498b48	internal/poll.(*FD).Read+0x178		/usr/local/go/src/internal/poll/fd_unix.go:169
#	0x5bb79e	net.(*netFD).Read+0x4e			/usr/local/go/src/net/fd_unix.go:202
#	0x5cf297	net.(*conn).Read+0x67			/usr/local/go/src/net/net.go:177
#	0x62b1f8	crypto/tls.(*block).readFromUntil+0x88	/usr/local/go/src/crypto/tls/conn.go:492
#	0x62b6fc	crypto/tls.(*Conn).readRecord+0xdc	/usr/local/go/src/crypto/tls/conn.go:593
#	0x62ec80	crypto/tls.(*Conn).Read+0xf0		/usr/local/go/src/crypto/tls/conn.go:1145
#	0x6e6464	net/http.(*persistConn).Read+0x74	/usr/local/go/src/net/http/transport.go:1497
#	0x516075	bufio.(*Reader).fill+0x105		/usr/local/go/src/bufio/bufio.go:100
#	0x5161ce	bufio.(*Reader).Peek+0x3e		/usr/local/go/src/bufio/bufio.go:132
#	0x6e6fb1	net/http.(*persistConn).readLoop+0x1a1	/usr/local/go/src/net/http/transport.go:1645
```

this stack also constantly grows in count of goroutine calling it, so SG tries to read , but doesn't get
a reply.

**Comment by stgleb** [comment] 2018-12-03 14:34
I've made a research on resource leak and get following result:

Main connection leak was between supergiant and kube-api when SG tried to pull metric from prometheus. For each metric request new http client and http transport were created with its own connection pool, so connections were not reused and opened all the time.

outbound connection growth rate 

```
while true ; do lsof| grep https| wc -l|tee -a outbound.txt ; sleep 10 ; done
2655
2775
2895
3015
3285
3525
3660
4005
4005
4080
4080
4080
5070
6150
7260
7995
8880
9780
10290
11835
13140
14415
15000
17504
18496
19936
21296
22496
23520
24496
24896
26224
27552
28800
29840
30704
32256
33776
35136
35632
36896
37888
38864
40352
40544
40656
41648
42512
43824
44672
45472
45520
45520
45520
45536
45536
45536
45536
45536
45536
45536
45536
45536
45536
45536
45552
45584
45680
45680
45712
45712
45728
45776
45776
45792
45856
45856
45856
```

After fixing it with reusing http.Client and http.Transport
connection growth rate had become less extreme, but the issue still exists. I've found that a lot of connections has been created on port 10250 which is a kubelet port. 

```
while true ; do lsof| grep 10250| wc -l|tee -a kubelet.txt ; sleep 10 ; done
18
18
319
334
409
454
454
454
454
454
454
454
454
454
454
454
454
454
454
514
634
1039
1444
1804
2239
2584
3004
3555
3891
4451
4467
4547
4547
4563
4707
4755
4772
4755
4755
4755
4755
4755
4755
4755
4755
4755
4755
4755
4755
4755
4755
4771
4771
4771
4771
4771
4771
4771
4771
4771
4771
4771
4771
4771
4771
4771
4771
4963
5603
5747
6035
6307
6819
6979
7411
7859
8227
```

This is already reported https://github.com/kubernetes/kubernetes/issues/67382 and has fix merged https://github.com/kubernetes/kubernetes/pull/68041 

After bumping k8s version to 1.11.5 that has this fix everything goes well

```
while true ; do lsof| grep 10250| wc -l|tee -a kubelet.txt ; sleep 10 ; done
19
19
19
19
35
19
19
19
35
99
67
35
115
78
83
19
115
83
51
22
35
67
67
35
35
94
99
35
19
93
67
19
83
99
35
19
115
83
67
19
67
67
92
19
115
67
67
19
35
99
83
83
35
35
85
67
35
99
83
67
19
115
67
83
35

while true ; do lsof| grep https| wc -l|tee -a outboud.txt ; sleep 10 ; done

208
208
208
208
208
208
208
224
208
208
224
304
272
224
208
256
288
224
208
288
256
294
224
304
271
272
224
288
256
224
224
288
272
224
304
257
288
208
208
304
304
224
224
288
288
208
224
256
304
240
224
304
304
240
224
224
272
304
224
304
304
272
208
224
272
288
224
208
```

**Closed** 2018-12-03 15:15 UTC
Labels: High Priority
