### ISSUE TITLE
aws node is created multiple times despite of  the error response from the server while creation request

### ISSUE THREAD

**Issue by nikage** [supergiant/control#1066] opened 2018-11-29 18:55 UTC
**Short Summary:**
After adding node to working cluster,  the server responds with 504 error but the node is created despite of that

**Steps to Reproduce:**
1. install sg control
2. create aws cluster
3. add node to working cluster 
4. after submitting finish button  

**Expected Results:**
node is not created

**Actual Results:**
multiple nodes created after error 

#logs from console:
```
control_plane_1  | time="2018-11-29T14:35:02Z" level=info msg="supergiant is starting on port 8080"
control_plane_1  | time="2018-11-29T18:39:15Z" level=info msg="[awskeypairstep] - importing cluster bootstrap key as keypair nick-aws-cl3-20a1-provision"
control_plane_1  | time="2018-11-29T18:39:15Z" level=error msg="[create_security_groups_step] - failed to whitelist supergiant IP in master security group: InvalidPermission.Duplicate: the specified rule \"peer: 83.142.233.249/32, TCP, from port: 8080, to port: 8080, ALLOW\" already exists\n\tstatus code: 400, request id: 9c8733e0-3177-4ee1-9005-d013eab4b5d2"
control_plane_1  | time="2018-11-29T18:39:16Z" level=error msg="Pre provisioning cluster cluster pre provisioning setup failed: InvalidKeyPair.Duplicate: The keypair 'nick-aws-cl3-20a1-provision' already exists.\n\tstatus code: 400, request id: f3ef4a24-beb3-4d1d-8693-288a1a588be2: aws: import keypair"
control_plane_1  | time="2018-11-29T18:39:16Z" level=info msg=create_subnet_step
control_plane_1  | time="2018-11-29T18:39:17Z" level=info msg=aws_create_instance
control_plane_1  | time="2018-11-29T18:39:19Z" level=info msg="[aws_create_instance] - using AMI (ID: ami-02f2ac62) Canonical, Ubuntu, 16.04 LTS, amd64 xenial image build on 2017-03-03"
control_plane_1  | time="2018-11-29T18:39:36Z" level=info msg=ssh
control_plane_1  | time="2018-11-29T18:39:36Z" level=info msg=add_authorized_keys
control_plane_1  | time="2018-11-29T18:40:02Z" level=info msg=download_kubernetes_binary
control_plane_1  | time="2018-11-29T18:40:14Z" level=info msg=certificates
control_plane_1  | time="2018-11-29T18:40:26Z" level=info msg=manifest
control_plane_1  | time="2018-11-29T18:40:38Z" level=info msg=flannel
control_plane_1  | time="2018-11-29T18:40:51Z" level=info msg=docker
control_plane_1  | time="2018-11-29T18:41:03Z" level=info msg=kubelet
control_plane_1  | time="2018-11-29T18:41:12Z" level=info msg="[awskeypairstep] - importing cluster bootstrap key as keypair nick-aws-cl3-20a1-provision"
control_plane_1  | time="2018-11-29T18:41:12Z" level=error msg="[create_security_groups_step] - failed to whitelist supergiant IP in master security group: InvalidPermission.Duplicate: the specified rule \"peer: 83.142.233.249/32, TCP, from port: 8080, to port: 8080, ALLOW\" already exists\n\tstatus code: 400, request id: d9be2d8f-d7cf-49c5-a123-123cc9bbe63b"
control_plane_1  | time="2018-11-29T18:41:13Z" level=error msg="Pre provisioning cluster cluster pre provisioning setup failed: InvalidKeyPair.Duplicate: The keypair 'nick-aws-cl3-20a1-provision' already exists.\n\tstatus code: 400, request id: 85940b42-c208-426c-87dc-fb585dceb5b5: aws: import keypair"
control_plane_1  | time="2018-11-29T18:41:13Z" level=info msg=create_subnet_step
control_plane_1  | time="2018-11-29T18:41:14Z" level=info msg=aws_create_instance
control_plane_1  | time="2018-11-29T18:41:15Z" level=info msg=cni
control_plane_1  | time="2018-11-29T18:41:16Z" level=info msg="[aws_create_instance] - using AMI (ID: ami-02f2ac62) Canonical, Ubuntu, 16.04 LTS, amd64 xenial image build on 2017-03-03"
control_plane_1  | time="2018-11-29T18:41:28Z" level=info msg=poststart
control_plane_1  | time="2018-11-29T18:41:33Z" level=info msg=ssh
control_plane_1  | time="2018-11-29T18:41:33Z" level=info msg=add_authorized_keys
control_plane_1  | time="2018-11-29T18:41:40Z" level=info msg="Task add5b548-fc4c-42de-95f4-b37c3b0ea038 has finished successfully"
control_plane_1  | time="2018-11-29T18:41:59Z" level=info msg=download_kubernetes_binary
control_plane_1  | time="2018-11-29T18:42:11Z" level=info msg=certificates
control_plane_1  | time="2018-11-29T18:42:24Z" level=info msg=manifest
control_plane_1  | time="2018-11-29T18:42:36Z" level=info msg=flannel
control_plane_1  | time="2018-11-29T18:42:48Z" level=info msg=docker
control_plane_1  | time="2018-11-29T18:43:00Z" level=info msg=kubelet
control_plane_1  | time="2018-11-29T18:43:13Z" level=info msg=cni
control_plane_1  | time="2018-11-29T18:43:25Z" level=info msg=poststart
control_plane_1  | time="2018-11-29T18:43:29Z" level=info msg="[awskeypairstep] - importing cluster bootstrap key as keypair nick-aws-cl3-20a1-provision"
control_plane_1  | time="2018-11-29T18:43:29Z" level=error msg="[create_security_groups_step] - failed to whitelist supergiant IP in master security group: InvalidPermission.Duplicate: the specified rule \"peer: 83.142.233.249/32, TCP, from port: 8080, to port: 8080, ALLOW\" already exists\n\tstatus code: 400, request id: 8627e747-aa1e-4939-b611-4279e66e45f5"
control_plane_1  | time="2018-11-29T18:43:30Z" level=error msg="Pre provisioning cluster cluster pre provisioning setup failed: InvalidKeyPair.Duplicate: The keypair 'nick-aws-cl3-20a1-provision' already exists.\n\tstatus code: 400, request id: 89c1b128-314c-4066-b6df-a118ce214d20: aws: import keypair"
control_plane_1  | time="2018-11-29T18:43:30Z" level=info msg=create_subnet_step
control_plane_1  | time="2018-11-29T18:43:31Z" level=info msg=aws_create_instance
control_plane_1  | time="2018-11-29T18:43:33Z" level=info msg="[aws_create_instance] - using AMI (ID: ami-02f2ac62) Canonical, Ubuntu, 16.04 LTS, amd64 xenial image build on 2017-03-03"
control_plane_1  | time="2018-11-29T18:43:37Z" level=info msg="Task 58972816-fcb6-4ac6-88d4-605061fc7ade has finished successfully"
control_plane_1  | time="2018-11-29T18:43:50Z" level=info msg=ssh
control_plane_1  | time="2018-11-29T18:43:50Z" level=info msg=add_authorized_keys
control_plane_1  | time="2018-11-29T18:44:16Z" level=info msg=download_kubernetes_binary
control_plane_1  | time="2018-11-29T18:44:28Z" level=info msg=certificates
control_plane_1  | time="2018-11-29T18:44:40Z" level=info msg=manifest
control_plane_1  | time="2018-11-29T18:44:53Z" level=info msg=flannel
control_plane_1  | time="2018-11-29T18:45:05Z" level=info msg=docker
control_plane_1  | time="2018-11-29T18:45:17Z" level=info msg=kubelet
control_plane_1  | time="2018-11-29T18:45:30Z" level=info msg=cni
control_plane_1  | time="2018-11-29T18:45:42Z" level=info msg=poststart
control_plane_1  | time="2018-11-29T18:45:55Z" level=info msg="Task 6803defa-f99f-40a5-a0bd-d70a788ab8e4 has finished successfully"
control_plane_1  | time="2018-11-29T18:49:33Z" level=error msg="helm: list releases: 20a1dfa1 cluster: list releases: setup port forwarding: forwarding ports: error upgrading connection: error sending request: Post https://54.193.70.178/api/v1/namespaces/kube-system/pods/tiller-deploy-7f4974b9c8-r2nbs/portforward: dial tcp 54.193.70.178:443: connect: connection timed out"
```

#nodes created:

![image](https://user-images.githubusercontent.com/42967644/49244700-1b0d0d00-f419-11e8-8627-e1a08d94a06f.png)

**Dev Info:** (add links to log files)
1. Output of `go version`:

2. Commit hash or release tag used (`git log`):
3. Number of Masters and Nodes:
4. Cloud Provider:
5. Logs from `/tasks/{task_id}/logs/ws` UI/API endpoint for involved clusters:
6. Log files from `/tmp`, on the machine Control is running on (for example: `/tmp/314c2c2c-62b7-461b-8022-04dabeb0d19d.log`):

**Comment by gopherstein** [comment] 2018-12-03 22:45
this appears to be a duplicate of this issue. https://github.com/supergiant/control/issues/1046

Closing, please re-open if this is not the case.

**Closed by gopherstein** 2018-12-03 22:45 UTC
Labels: High Priority, bug
